// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {library} from '../models';
import {profile} from '../models';

export function ActivateProfile(arg1:string,arg2:string):Promise<void>;

export function AddPluginFromZip(arg1:string):Promise<library.Plugin>;

export function GetPlugins():Promise<Array<library.Plugin>>;

export function GetProfiles():Promise<Array<profile.Profile>>;

export function Greet(arg1:string):Promise<string>;

export function LaunchAviUtl(arg1:string):Promise<void>;

export function SaveProfile(arg1:profile.Profile):Promise<void>;
