// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateProfile(arg1, arg2) {
  return window['go']['main']['App']['ActivateProfile'](arg1, arg2);
}

export function AddPluginFromZip(arg1) {
  return window['go']['main']['App']['AddPluginFromZip'](arg1);
}

export function GetPlugins() {
  return window['go']['main']['App']['GetPlugins']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LaunchAviUtl(arg1) {
  return window['go']['main']['App']['LaunchAviUtl'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}
